/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'product-collections': ProductCollection;
    'product-category-urls': ProductCategoryUrl;
    'hero-sections': HeroSection;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'product-collections': ProductCollectionsSelect<false> | ProductCollectionsSelect<true>;
    'product-category-urls': ProductCategoryUrlsSelect<false> | ProductCategoryUrlsSelect<true>;
    'hero-sections': HeroSectionsSelect<false> | HeroSectionsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Assign roles to determine user permissions.
   */
  roles: ('admin' | 'user')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-collections".
 */
export interface ProductCollection {
  id: string;
  order?: number | null;
  name: string;
  url: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-category-urls".
 */
export interface ProductCategoryUrl {
  id: string;
  category: string;
  key: string;
  urls?:
    | {
        url: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-sections".
 */
export interface HeroSection {
  id: string;
  name?: string | null;
  backgroundType?: ('color' | 'image' | 'video' | 'gradient') | null;
  backgroundColor?: string | null;
  backgroundImage?: (string | null) | Media;
  backgroundVideo?: (string | null) | Media;
  backgroundGradient?: {
    from?: string | null;
    to?: string | null;
    direction?: ('to-r' | 'to-l' | 'to-b' | 'to-t' | 'to-br' | 'to-bl' | 'to-tr' | 'to-tl') | null;
  };
  backgroundPattern?: {
    type?: ('none' | 'dots' | 'grid' | 'waves' | 'triangles') | null;
    color?: string | null;
    opacity?: number | null;
    size?: ('small' | 'medium' | 'large') | null;
    animated?: boolean | null;
  };
  backgroundImageOverlay?: {
    color?: string | null;
    blendMode?: ('normal' | 'multiply' | 'screen' | 'overlay' | 'darken' | 'lighten') | null;
  };
  contentAlignment?: {
    textAlignment?: ('text-left' | 'text-center' | 'text-right') | null;
    verticalAlignment?: ('items-start' | 'items-center' | 'items-end') | null;
    maxWidth?:
      | (
          | 'max-w-sm'
          | 'max-w-md'
          | 'max-w-lg'
          | 'max-w-xl'
          | 'max-w-2xl'
          | 'max-w-3xl'
          | 'max-w-4xl'
          | 'max-w-5xl'
          | 'max-w-6xl'
          | 'max-w-7xl'
          | 'max-w-full'
        )
      | null;
  };
  spacing?: {
    paddingTop?: string | null;
    paddingBottom?: string | null;
    paddingX?: string | null;
  };
  headline?: {
    text?: string | null;
    style?: ('sans' | 'serif' | 'mono' | 'display' | 'handwriting') | null;
    size?:
      | (
          | 'text-xs'
          | 'text-sm'
          | 'text-base'
          | 'text-lg'
          | 'text-xl'
          | 'text-2xl'
          | 'text-3xl'
          | 'text-4xl'
          | 'text-5xl'
          | 'text-6xl'
          | 'text-7xl'
          | 'text-8xl'
          | 'text-9xl'
        )
      | null;
    color?: string | null;
    bold?: boolean | null;
    italic?: boolean | null;
    letterSpacing?: ('-0.05em' | '-0.025em' | '0' | '0.025em' | '0.05em' | '0.1em') | null;
    textShadow?: string | null;
    highlight?: string | null;
    transform?: ('normal' | 'uppercase' | 'lowercase' | 'capitalize') | null;
    decoration?: ('none' | 'underline' | 'line-through') | null;
  };
  subHeadline?: {
    text?: string | null;
    style?: ('sans' | 'serif' | 'mono' | 'display' | 'handwriting') | null;
    size?:
      | (
          | 'text-xs'
          | 'text-sm'
          | 'text-base'
          | 'text-lg'
          | 'text-xl'
          | 'text-2xl'
          | 'text-3xl'
          | 'text-4xl'
          | 'text-5xl'
          | 'text-6xl'
          | 'text-7xl'
          | 'text-8xl'
          | 'text-9xl'
        )
      | null;
    color?: string | null;
    bold?: boolean | null;
    italic?: boolean | null;
    letterSpacing?: ('-0.05em' | '-0.025em' | '0' | '0.025em' | '0.05em' | '0.1em') | null;
    textShadow?: string | null;
    highlight?: string | null;
    transform?: ('normal' | 'uppercase' | 'lowercase' | 'capitalize') | null;
    decoration?: ('none' | 'underline' | 'line-through') | null;
  };
  supportingText?: {
    text?: string | null;
    style?: ('sans' | 'serif' | 'mono' | 'display' | 'handwriting') | null;
    size?:
      | (
          | 'text-xs'
          | 'text-sm'
          | 'text-base'
          | 'text-lg'
          | 'text-xl'
          | 'text-2xl'
          | 'text-3xl'
          | 'text-4xl'
          | 'text-5xl'
          | 'text-6xl'
          | 'text-7xl'
          | 'text-8xl'
          | 'text-9xl'
        )
      | null;
    color?: string | null;
    bold?: boolean | null;
    italic?: boolean | null;
    letterSpacing?: ('-0.05em' | '-0.025em' | '0' | '0.025em' | '0.05em' | '0.1em') | null;
    textShadow?: string | null;
    highlight?: string | null;
    transform?: ('normal' | 'uppercase' | 'lowercase' | 'capitalize') | null;
    decoration?: ('none' | 'underline' | 'line-through') | null;
  };
  ctaButtons?:
    | {
        text?: string | null;
        url?: string | null;
        style?: ('primary' | 'secondary' | 'outline' | 'ghost' | 'link' | 'gradient') | null;
        size?: ('small' | 'medium' | 'large') | null;
        icon?: string | null;
        iconPosition?: ('left' | 'right') | null;
        customColors?: {
          background?: string | null;
          text?: string | null;
          border?: string | null;
          hoverBackground?: string | null;
          hoverText?: string | null;
        };
        animation?: ('none' | 'pulse' | 'bounce' | 'shake' | 'glow') | null;
        id?: string | null;
      }[]
    | null;
  sideContent?:
    | {
        type?: ('image' | 'video' | 'shape') | null;
        source?: (string | null) | Media;
        altText?: string | null;
        width?: string | null;
        height?: string | null;
        animation?: ('none' | 'float' | 'rotate' | 'slide' | 'fade') | null;
        position?: ('left' | 'right') | null;
        offset?: string | null;
        zIndex?: number | null;
        id?: string | null;
      }[]
    | null;
  layoutType?: ('centered' | 'split' | 'offset' | 'stacked') | null;
  divider?: {
    show?: boolean | null;
    type?: ('wave' | 'curve' | 'triangle' | 'chevron' | 'straight') | null;
    color?: string | null;
    height?: string | null;
    position?: ('top' | 'bottom') | null;
  };
  animation?: {
    entrance?: ('fade' | 'slide' | 'zoom' | 'none') | null;
    speed?: ('slow' | 'medium' | 'fast') | null;
    stagger?: boolean | null;
  };
  customClass?: string | null;
  minHeight?: string | null;
  borderRadius?:
    | (
        | 'rounded-none'
        | 'rounded'
        | 'rounded-md'
        | 'rounded-lg'
        | 'rounded-xl'
        | 'rounded-2xl'
        | 'rounded-3xl'
        | 'rounded-full'
        | 'custom'
      )
    | null;
  boxShadow?: ('none' | 'sm' | 'md' | 'lg' | 'xl') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'product-collections';
        value: string | ProductCollection;
      } | null)
    | ({
        relationTo: 'product-category-urls';
        value: string | ProductCategoryUrl;
      } | null)
    | ({
        relationTo: 'hero-sections';
        value: string | HeroSection;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-collections_select".
 */
export interface ProductCollectionsSelect<T extends boolean = true> {
  order?: T;
  name?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-category-urls_select".
 */
export interface ProductCategoryUrlsSelect<T extends boolean = true> {
  category?: T;
  key?: T;
  urls?:
    | T
    | {
        url?: T;
        label?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-sections_select".
 */
export interface HeroSectionsSelect<T extends boolean = true> {
  name?: T;
  backgroundType?: T;
  backgroundColor?: T;
  backgroundImage?: T;
  backgroundVideo?: T;
  backgroundGradient?:
    | T
    | {
        from?: T;
        to?: T;
        direction?: T;
      };
  backgroundPattern?:
    | T
    | {
        type?: T;
        color?: T;
        opacity?: T;
        size?: T;
        animated?: T;
      };
  backgroundImageOverlay?:
    | T
    | {
        color?: T;
        blendMode?: T;
      };
  contentAlignment?:
    | T
    | {
        textAlignment?: T;
        verticalAlignment?: T;
        maxWidth?: T;
      };
  spacing?:
    | T
    | {
        paddingTop?: T;
        paddingBottom?: T;
        paddingX?: T;
      };
  headline?:
    | T
    | {
        text?: T;
        style?: T;
        size?: T;
        color?: T;
        bold?: T;
        italic?: T;
        letterSpacing?: T;
        textShadow?: T;
        highlight?: T;
        transform?: T;
        decoration?: T;
      };
  subHeadline?:
    | T
    | {
        text?: T;
        style?: T;
        size?: T;
        color?: T;
        bold?: T;
        italic?: T;
        letterSpacing?: T;
        textShadow?: T;
        highlight?: T;
        transform?: T;
        decoration?: T;
      };
  supportingText?:
    | T
    | {
        text?: T;
        style?: T;
        size?: T;
        color?: T;
        bold?: T;
        italic?: T;
        letterSpacing?: T;
        textShadow?: T;
        highlight?: T;
        transform?: T;
        decoration?: T;
      };
  ctaButtons?:
    | T
    | {
        text?: T;
        url?: T;
        style?: T;
        size?: T;
        icon?: T;
        iconPosition?: T;
        customColors?:
          | T
          | {
              background?: T;
              text?: T;
              border?: T;
              hoverBackground?: T;
              hoverText?: T;
            };
        animation?: T;
        id?: T;
      };
  sideContent?:
    | T
    | {
        type?: T;
        source?: T;
        altText?: T;
        width?: T;
        height?: T;
        animation?: T;
        position?: T;
        offset?: T;
        zIndex?: T;
        id?: T;
      };
  layoutType?: T;
  divider?:
    | T
    | {
        show?: T;
        type?: T;
        color?: T;
        height?: T;
        position?: T;
      };
  animation?:
    | T
    | {
        entrance?: T;
        speed?: T;
        stagger?: T;
      };
  customClass?: T;
  minHeight?: T;
  borderRadius?: T;
  boxShadow?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}